-- Create the market_proposals table
create table market_proposals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  description text not null,
  category text not null,
  end_time bigint not null, -- Unix timestamp for when the market resolves
  status text default 'pending', -- 'pending', 'approved', 'declined'
  feedback text, -- Admin feedback
  source text -- e.g., 'ai-bot', 'manual-script'
);

-- Enable Row Level Security (RLS)
alter table market_proposals enable row level security;

-- Policies
-- Allow Read access to everyone (or just admins if we want to be strict, but anon is easier for now)
create policy "Enable read access for all users" on market_proposals for select using (true);

-- Allow Insert access for all users (so the bot can insert using anon key, or we used service key)
-- ideally restricted, but for this demo/MVP we allow anon insert for the 'bot'
create policy "Enable insert for all users" on market_proposals for insert with check (true);

-- Allow Update for all users (so admin can approve/decline)
create policy "Enable update for all users" on market_proposals for update using (true);
