-- ==========================================
-- Market Proposals
-- ==========================================
create table if not exists market_proposals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  description text not null,
  category text not null,
  end_time bigint not null,
  status text default 'pending',
  feedback text,
  source text
);

alter table market_proposals enable row level security;

-- Drop existing policies to allow re-running this script
drop policy if exists "Enable read access for all users" on market_proposals;
drop policy if exists "Enable insert for all users" on market_proposals;
drop policy if exists "Enable update for all users" on market_proposals;

create policy "Enable read access for all users" on market_proposals for select using (true);
create policy "Enable insert for all users" on market_proposals for insert with check (true);
create policy "Enable update for all users" on market_proposals for update using (true);

-- ==========================================
-- Markets Metadata (For frontend visibility)
-- ==========================================
-- We assume this table might exist. If not, create a basic structure (optional)
create table if not exists markets_metadata (
  market_id bigint primary key,
  title text,
  status text, -- 'Open', 'Resolved', etc.
  category text,
  long_description text
  -- Add other columns as needed
);

alter table markets_metadata enable row level security;

drop policy if exists "Enable all access for markets_metadata" on markets_metadata;
create policy "Enable all access for markets_metadata" on markets_metadata for all using (true) with check (true);

-- ==========================================
-- User Peeps (Bets tracking)
-- ==========================================
create table if not exists user_peeps (
  id bigint generated by default as identity primary key,
  user_address text not null,
  market_id bigint not null,
  outcome smallint not null,
  amount text, -- Storing BigInt as text is common to avoid overflow in JS/JSON
  timestamp bigint
);

alter table user_peeps enable row level security;

drop policy if exists "Enable all access for user_peeps" on user_peeps;
create policy "Enable all access for user_peeps" on user_peeps for all using (true) with check (true);
